### PR TITLE
Update bindgen build dependency to 0.51

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Comment by repi** [comment]
We've had a fork that does this too, would be great to merge this into master and publish a new release with it

**Comment by est31** [comment]
I've merged this and will do a 0.2.3 release at the end of the week (unless @mitchmindtree beats me to it).

**Comment by est31** [comment]
Any idea why CI is failing on master?

**Comment by glandium** [comment]
See https://github.com/RustAudio/coreaudio-sys/pull/28/commits/7a51ced741ebd1c35eeef54ce641127d82ff2281

I guess changes in rustfmt 0.51might have broken CI finding the rustfmt executable.

**Comment by est31** [comment]
> The job exceeded the maximum log length, and has been terminated.

Hmm yeah that might be the issue: https://github.com/rust-lang/rust-bindgen/issues/1600

I'll add a local workaround for this repo until the upstream bug is resolved.

**Comment by est31** [comment]
I guess we'll need [this](https://github.com/rust-lang/rust-bindgen/commit/d1ddfbba23f074bb4df11a1efd5c99e944638744) commit or set rustfmt in another way. I've filed #31 for experimentation.

**Pull request merged**
