### PR TITLE
Support Linux Cross Compiling

### PR DESCRIPTION
**Pull request by zicklag**
Add extra configuration through environment variables to allow compiling for MacOS on Linux. iOS might be possible as well, but it is untested.

This is an attempt at fixing #23.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Thank a lot for this!

Would you mind adding a section to the README that describes how to use the env var to cross compile for macOS from Linux? I'm afraid this might go hidden otherwise!

**Comment by zicklag** [comment]
No problem. :slightly_smiling_face: I'll add the README changes as soon as I get the chance.

**Comment by zicklag** [comment]
There you go.

**Comment by zicklag** [comment]
Just a friendly reminder, is there anything else needed to get this merged?

**Comment by mitchmindtree** [comment]
Sorry about the delay and thanks again!

**Pull request merged**
